spring:
  application:
    name: gym-crm
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  liquibase:
    change-log: classpath:db/migration/master.xml
    enabled: true

app:
  api:
    base-path: /api/v1